<a href="https://colab.research.google.com/github/Car27VeP/Data_Science_Projects/blob/main/An%C3%A1lisis_de_Valor_de_Vida_del_Cliente_(LTV)_Simplificado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Una app me ha contratado para saber quienes son sus mejores cliente desde su base de datos y por qué.

In [ ]:
import pandas as pd
import numpy as np

# Creamos datos ficticios de una App de suscripción
np.random.seed(42)
n_clientes = 200
data = {
    'cliente_id': range(1, n_clientes + 1),
    'meses_antiguedad': np.random.randint(1, 24, n_clientes),
    'gasto_mensual': np.random.uniform(10, 100, n_clientes),
    'soporte_tecnico_clicks': np.random.poisson(2, n_clientes),
    'dispositivo': np.random.choice(['iOS', 'Android', 'Web'], n_clientes)
}
df = pd.DataFrame(data)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   cliente_id              200 non-null    int64
 1   meses_antiguedad        200 non-null    int64
 2   gasto_mensual           200 non-null    float64
 3   soporte_tecnico_clicks  200 non-null    int64
 4   dispositivo             200 non-null    object
dtypes: float64(1), int64(3), object(1)
memory usage: 7.9+ KB

In [ ]:
df.describe()

       cliente_id  meses_antiguedad  gasto_mensual  soporte_tecnico_clicks
count  200.000000        200.000000     200.000000              200.000000
mean   100.500000         11.530000      55.060910                1.910000
std     57.879185          6.686001      25.956747                1.407767
min      1.000000          1.000000      10.455543                0.000000
25%     50.750000          6.000000      32.211609                1.000000
50%    100.500000         11.500000      57.745234                2.000000
75%    150.250000         17.000000      75.339063                3.000000
max    200.000000         23.000000      99.104847                8.000000

In [ ]:
df.head()

,cliente_id,meses_antiguedad,gasto_mensual,soporte_tecnico_clicks,dispositivo
0,1,7,35.078182,4,Web
1,2,20,91.743930,0,Android
2,3,15,31.560570,1,Android
3,4,11,23.040538,3,Android
4,5,8,54.050748,4,iOS

Para saber quienes son los clientes VIP, calculamos el gasto mensual por los meses de antiguedad por usuario y ese resultado tiene que ser mayor a su promedio.

In [ ]:
df['LTV_estimado'] = df['gasto_mensual'] * df['meses_antiguedad']
df['Perfil_Cliente'] = np.where(df['LTV_estimado']>df['LTV_estimado'].mean(),'VIP','Estandar')

In [ ]:
df['Perfil_Cliente'].value_counts()

Perfil_Cliente
Estandar    116
VIP          84
Name: count, dtype: int64

In [ ]:
df['dispositivo'].value_counts()

dispositivo
Web        68
Android    67
iOS        65
Name: count, dtype: int64

In [ ]:
# ¿Qué dispositivo prefieren nuestros VIPs?
df.groupby('dispositivo')['LTV_estimado'].mean().sort_values(ascending=False)

dispositivo
iOS        712.156667
Android    605.114743
Web        516.943424
Name: LTV_estimado, dtype: float64

Hemos identificado 84 clientes VIP. Esto ayuda a la empresa saber quienes son y poner atencion a estos usuarios para que sigan siendo clientes VIP ofreciendoles promociones de descuento por clientes leales.